# Generated by Django 5.2.1 on 2025-05-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='kategori',
        ),
        migrations.RemoveField(
            model_name='product',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='table_status',
        ),
        migrations.AddField(
            model_name='product',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='kode',
            field=models.CharField(default=1000, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nama',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status_menu',
            field=models.BooleanField(default=True),
        ),
    ]
